services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      VITE_PROXY_TARGET: http://backend:8000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    environment:
      WATCHFILES_FORCE_POLLING: 'true'
    volumes:
      - ./backend:/app

volumes:
  frontend_node_modules:
